apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: keycloak
  namespace: argocd-olm-manual-approval
spec:
  externalAccess:
    enabled: true
  instances: 1
